test

diff --git a/.github/workflows/Release-Linux.yml b/.github/workflows/Release-Linux.yml
--- a/.github/workflows/Release-Linux.yml
+++ b/.github/workflows/Release-Linux.yml
@@ -19,7 +19,9 @@ jobs:
       PYO3_USE_ABI3_FORWARD_COMPATIBILITY: 1
       TARGET: x86_64-unknown-linux-gnu
       BINARY_NAME: adqa-tui-linux-x86_64
-      PYTHON_URL: "https://github.com/astral-sh/python-build-standalone/releases/download/20240107/cpython-3.12.1+20240107-x86_64-unknown-linux-gnu-pgo+lto-full.tar.zst"
+      PYTHON_URL: "https://github.com/astral-sh/python-build-standalone/releases/download/20260211/cpython-3.12.12+20260211-x86_64-unknown-linux-gnu-install_only_stripped.tar.gz"
+      PYTHON_SHA256: "1dbaa624a09e15afe7efbdac08d42993135a68db8d34f986ef6977a6d77bdc3c"
+
     steps:
       - uses: actions/checkout@v6
       - name: Set up Rust
@@ -27,10 +29,10 @@ jobs:
         with:
           targets: ${{ env.TARGET }}
 
-      - name: Install Build Dependencies
-        run: |
-          sudo apt-get update
-          sudo apt-get install -y libreadline-dev libedit-dev libncursesw5-dev libsqlite3-dev libssl-dev libffi-dev libexpat1-dev libbz2-dev liblzma-dev uuid-dev zlib1g-dev tcl-dev tk-dev libx11-dev libxcb1-dev libxau-dev
+      # - name: Install Build Dependencies
+      #   run: |
+      #     sudo apt-get update
+      #     sudo apt-get install -y libreadline-dev libedit-dev libncursesw5-dev libsqlite3-dev libssl-dev libffi-dev libexpat1-dev libbz2-dev liblzma-dev uuid-dev zlib1g-dev tcl-dev tk-dev libx11-dev libxcb1-dev libxau-dev
 
       - name: Setup Standalone Python
         shell: bash
@@ -38,6 +40,10 @@ jobs:
           mkdir -p standalone_python
           cd standalone_python
           curl -sfSL "${{ env.PYTHON_URL }}" -o python.tar.zst
+
+          # checksum check
+          echo "$PYTHON_SHA256  python.tar.gz" | sha256sum -c -
+
           tar -xf python.tar.zst
           mv python/install ../python_env
           cd ..
@@ -50,29 +56,29 @@ jobs:
         working-directory: adqa-tui
         shell: bash
         run: |
-          PYTHON_ROOT_DIR=$(realpath "../python_env")
-          LIB_SO=$(find "$PYTHON_ROOT_DIR" -name "libpython3.12.so*" | head -n 1)
-          if [ -z "$LIB_SO" ]; then
-            echo "Error: libpython3.12.so not found"
-            exit 1
-          fi
-          LIB_DIR=$(dirname "$LIB_SO")
+          # PYTHON_ROOT_DIR=$(realpath "../python_env")
+          # LIB_SO=$(find "$PYTHON_ROOT_DIR" -name "libpython3.12.so*" | head -n 1)
+          # if [ -z "$LIB_SO" ]; then
+          #   echo "Error: libpython3.12.so not found"
+          #   exit 1
+          # fi
+          # LIB_DIR=$(dirname "$LIB_SO")
           
-          cat <<CONF | sed 's/^[[:space:]]*//' > ../pyo3-config.txt
-          implementation=CPython
-          version=3.12
-          shared=true
-          lib_name=python3.12
-          lib_dir=$LIB_DIR
-          pointer_width=64
-          build_flags=
-          CONF
+          # cat <<CONF | sed 's/^[[:space:]]*//' > ../pyo3-config.txt
+          # implementation=CPython
+          # version=3.12
+          # shared=true
+          # lib_name=python3.12
+          # lib_dir=$LIB_DIR
+          # pointer_width=64
+          # build_flags=
+          # CONF
           
-          export PYO3_CONFIG_FILE="$(pwd)/../pyo3-config.txt"
+          # export PYO3_CONFIG_FILE="$(pwd)/../pyo3-config.txt"
           
-          # Use shared linking and set RPATH so the binary finds libpython3.12.so in the bundle
-          # $ORIGIN refers to the directory containing the executable
-          export RUSTFLAGS="-L $LIB_DIR -Clink-arg=-Wl,-rpath,\$ORIGIN/python/lib"
+          # # Use shared linking and set RPATH so the binary finds libpython3.12.so in the bundle
+          # # $ORIGIN refers to the directory containing the executable
+          # export RUSTFLAGS="-L $LIB_DIR -Clink-arg=-Wl,-rpath,\$ORIGIN/python/lib"
           
           cargo build --release --target ${{ env.TARGET }}
 
@@ -81,6 +87,7 @@ jobs:
         run: |
           mkdir -p adqa-tui-bundle
           cp adqa-tui/target/${{ env.TARGET }}/release/adqa-tui adqa-tui-bundle/${{ env.BINARY_NAME }}
+          cp adqa-tui/target/${{ env.TARGET }}/release/adqa-cli adqa-tui-bundle/${{ env.BINARY_NAME }}
           cp -r python_env adqa-tui-bundle/python
           rm -rf adqa-tui-bundle/python/share adqa-tui-bundle/python/include
           find adqa-tui-bundle/python -name "__pycache__" -type d -exec rm -rf {} + || true
