test

diff --git a/.github/workflows/Release-Linux.yml b/.github/workflows/Release-Linux.yml
--- a/.github/workflows/Release-Linux.yml
+++ b/.github/workflows/Release-Linux.yml
@@ -16,7 +16,6 @@ jobs:
   build-linux:
     runs-on: ubuntu-latest
     env:
-      # PYO3_USE_ABI3_FORWARD_COMPATIBILITY: 1
       TARGET: x86_64-unknown-linux-gnu
       BINARY_NAME: adqa-${{ startsWith(github.ref, 'refs/tags/') && github.ref_name || 'v0.0.0' }}-linux-x86_64-unknown-linux-gnu
       PYTHON_URL: "https://github.com/astral-sh/python-build-standalone/releases/download/20260211/cpython-3.12.12+20260211-x86_64-unknown-linux-gnu-install_only_stripped.tar.gz"
@@ -56,25 +55,25 @@ jobs:
         working-directory: adqa-tui
         shell: bash
         run: |
-          # PYTHON_ROOT_DIR=$(realpath "../python_env")
-          # LIB_SO=$(find "$PYTHON_ROOT_DIR" -name "libpython3.12.so*" | head -n 1)
-          # if [ -z "$LIB_SO" ]; then
-          #   echo "Error: libpython3.12.so not found"
-          #   exit 1
-          # fi
-          # LIB_DIR=$(dirname "$LIB_SO")
+          PYTHON_ROOT_DIR=$(realpath "../python_env")
+          LIB_SO=$(find "$PYTHON_ROOT_DIR" -name "libpython3.12.so*" | head -n 1)
+          if [ -z "$LIB_SO" ]; then
+            echo "Error: libpython3.12.so not found"
+            exit 1
+          fi
+          LIB_DIR=$(dirname "$LIB_SO")
           
-          # cat <<CONF | sed 's/^[[:space:]]*//' > ../pyo3-config.txt
-          # implementation=CPython
-          # version=3.12
-          # shared=true
-          # lib_name=python3.12
-          # lib_dir=$LIB_DIR
-          # pointer_width=64
-          # build_flags=
-          # CONF
+          cat <<CONF | sed 's/^[[:space:]]*//' > ../pyo3-config.txt
+          implementation=CPython
+          version=3.12
+          shared=true
+          lib_name=python3.12
+          lib_dir=$LIB_DIR
+          pointer_width=64
+          build_flags=
+          CONF
           
-          # export PYO3_CONFIG_FILE="$(pwd)/../pyo3-config.txt"
+          export PYO3_CONFIG_FILE="$(pwd)/../pyo3-config.txt"
           
           # Use shared linking and set RPATH so the binary finds libpython3.12.so in the bundle
           # $ORIGIN refers to the directory containing the executable
